var data = {
	fuente : 'Web Service',
    empresa: 'EDESUR',
    totalUsuariosSinSuministro: '8.196',
    totalUsuariosConSuministro: '2.525.984',
    ultimaActualizacion: '16:40',
    totalUsuariosAyer: '151.891',
    cortesPreventivos:  [],
    cortesProgramados:  [],
    cortesServicioMedia:  [{partido: 'BERAZATEGUI',localidad: 'BERAZATEGUI CENTRO',subestacion_alimentador: '80-EZPELETA / R:080-1-05 / 080-1-05',usuarios: '1450',normalizacion: 'Sin datos'},{partido: 'BERAZATEGUI',localidad: 'V. ESPAÑA',subestacion_alimentador: '80-EZPELETA / R:080-1-05 / 080-1-05',usuarios: '553',normalizacion: 'Sin datos'},{partido: 'CAÑUELAS',localidad: 'ZONA RURAL 7',subestacion_alimentador: '271-CAnUELAS / R:271-2-26 / 271-2-26 / 271-2-27',usuarios: '2',normalizacion: 'Sin datos'},{partido: 'CAÑUELAS',localidad: 'ZONA RURAL 8',subestacion_alimentador: '271-CAnUELAS / R:271-2-26 / 271-2-26 / 271-2-27',usuarios: '10',normalizacion: 'Sin datos'},{partido: 'CAPITAL FEDERAL',localidad: 'ALMAGRO',subestacion_alimentador: '49-PARQUE CENTENARIO / R:049-4-46 / 049-4-46',usuarios: '263',normalizacion: '2019-01-31 20:10'},{partido: 'CAPITAL FEDERAL',localidad: 'LA PATERNAL',subestacion_alimentador: '147-VILLA CRESPO / R:147-2-28 / 147-2-28',usuarios: '1119',normalizacion: '2019-01-31 18:34'},{partido: 'CAPITAL FEDERAL',localidad: 'MONSERRAT',subestacion_alimentador: '210-CARLOS PELLEGRINI / R:210-2-16 / 210-2-16',usuarios: '67',normalizacion: '2019-01-31 18:20'},{partido: 'CAPITAL FEDERAL',localidad: 'RECOLETA',subestacion_alimentador: '21-AZCUENAGA / R:021-2-24 / 021-2-24',usuarios: '625',normalizacion: 'Sin datos'},{partido: 'CAPITAL FEDERAL',localidad: 'VILLA SOLDATI RP',subestacion_alimentador: '39-POMPEYA / R:039-1-13 / 039-1-13',usuarios: '230',normalizacion: '2019-01-31 18:33'},{partido: 'EZEIZA',localidad: 'TRISTAN SUAREZ',subestacion_alimentador: '270-SPEGAZZINI / R:270-1-14 / 270-1-14',usuarios: '416',normalizacion: '2019-01-31 18:11'},{partido: 'LOMAS DE ZAMORA',localidad: 'LOMAS DE ZAMORA',subestacion_alimentador: '182-SANTA CATALINA / R:182-2-28 / 182-2-28',usuarios: '402',normalizacion: 'Sin datos'},{partido: 'SAN VICENTE',localidad: 'SAN VICENTE',subestacion_alimentador: '271-CAnUELAS / R:271-2-26 / 271-2-26 / 271-2-27',usuarios: '6',normalizacion: 'Sin datos'}],
    cortesComunicados:  [],
    cortesServicioBaja:  [ {partido: 'ALMIRANTE BROWN', localidad: 'ADROGUE', usuarios: '36'}, {partido: 'ALMIRANTE BROWN', localidad: 'BURZACO', usuarios: '100'}, {partido: 'ALMIRANTE BROWN', localidad: 'CLAYPOLE', usuarios: '13'}, {partido: 'ALMIRANTE BROWN', localidad: 'GLEW', usuarios: '12'}, {partido: 'ALMIRANTE BROWN', localidad: 'MARMOL', usuarios: '121'}, {partido: 'AVELLANEDA', localidad: 'SARANDI', usuarios: '11'}, {partido: 'BERAZATEGUI', localidad: 'BERAZATEGUI', usuarios: '156'}, {partido: 'CAÑUELAS', localidad: 'CAÑUELAS', usuarios: '8'}, {partido: 'CAPITAL', localidad: 'BALVANERA', usuarios: '182'}, {partido: 'CAPITAL', localidad: 'BARRACAS', usuarios: '2'}, {partido: 'CAPITAL', localidad: 'BOEDO', usuarios: '152'}, {partido: 'CAPITAL', localidad: 'CABALLITO', usuarios: '51'}, {partido: 'CAPITAL', localidad: 'CAPITAL', usuarios: '137'}, {partido: 'CAPITAL', localidad: 'CONSTITUCION', usuarios: '11'}, {partido: 'CAPITAL', localidad: 'FLORES', usuarios: '50'}, {partido: 'CAPITAL', localidad: 'FLORESTA', usuarios: '22'}, {partido: 'CAPITAL', localidad: 'LA BOCA', usuarios: '147'}, {partido: 'CAPITAL', localidad: 'LA PATERNAL', usuarios: '7'}, {partido: 'CAPITAL', localidad: 'LINIERS', usuarios: '16'}, {partido: 'CAPITAL', localidad: 'MATADEROS', usuarios: '259'}, {partido: 'CAPITAL', localidad: 'PARQUE AVELLANEDA', usuarios: '87'}, {partido: 'CAPITAL', localidad: 'PARQUE PATRICIOS', usuarios: '64'}, {partido: 'CAPITAL', localidad: 'RECOLETA', usuarios: '64'}, {partido: 'CAPITAL', localidad: 'RETIRO', usuarios: '39'}, {partido: 'CAPITAL', localidad: 'SAN CRISTOBAL', usuarios: '69'}, {partido: 'CAPITAL', localidad: 'SAN NICOLAS', usuarios: '28'}, {partido: 'CAPITAL', localidad: 'VILLA CRESPO', usuarios: '63'}, {partido: 'CAPITAL', localidad: 'VILLA DEL PARQUE', usuarios: '25'}, {partido: 'CAPITAL', localidad: 'VILLA DEVOTO', usuarios: '125'}, {partido: 'CAPITAL', localidad: 'VILLA LUGANO', usuarios: '28'}, {partido: 'CAPITAL', localidad: 'VILLA LURO', usuarios: '20'}, {partido: 'CAPITAL', localidad: 'VILLA RIACHUELO', usuarios: '167'}, {partido: 'CAPITAL', localidad: 'VILLA SOLDATI', usuarios: '1'}, {partido: 'CAPITAL', localidad: 'VILLA STA. RITA', usuarios: '88'}, {partido: 'ESTEBAN ECHEVERRIA', localidad: '9 DE ABRIL', usuarios: '26'}, {partido: 'ESTEBAN ECHEVERRIA', localidad: 'LUIS GUILLON', usuarios: '19'}, {partido: 'ESTEBAN ECHEVERRIA', localidad: 'MONTE GRANDE', usuarios: '93'}, {partido: 'EZEIZA', localidad: 'TRISTAN SUAREZ', usuarios: '5'}, {partido: 'LANUS', localidad: 'MONTE CHINGOLO', usuarios: '83'}, {partido: 'LANUS', localidad: 'VALENTIN ALSINA', usuarios: '65'}, {partido: 'LOMAS DE ZAMORA', localidad: 'INGENIERO BUDGE', usuarios: '27'}, {partido: 'LOMAS DE ZAMORA', localidad: 'LOMAS DE ZAMORA', usuarios: '208'}, {partido: 'LOMAS DE ZAMORA', localidad: 'TEMPERLEY', usuarios: '24'}, {partido: 'QUILMES', localidad: 'DON BOSCO', usuarios: '28'}, {partido: 'QUILMES', localidad: 'QUILMES', usuarios: '114'}]
  }		
		